--EASY
-- Q1 Calculate the total revenue generated in millions for the entire dataset with the currency.
SELECT CONCAT('$',ROUND(SUM(order_quantity * product_price)/1000000,1),'M') as overall_sales
FROM sales_data s
JOIN product_lookup p
ON s.product_key = p.product_key;

--Q2 Write a series of queries that aggregate total revenue and order frequency across Gender, Marital Status, Occupation, and Education Level.

--gender
SELECT 
	gender,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY gender
ORDER BY revenue DESC;

--marital_Status
SELECT 
	marital_Status,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY marital_Status
ORDER BY revenue DESC;

--occupation
SELECT 
	occupation,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY occupation
ORDER BY revenue DESC;

--education_level
SELECT 
	education_level,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY education_level
ORDER BY revenue DESC;

--Q3 List the total revenue for each month
SELECT 
	extract(MONTH from c.date) as month,
	to_char(date::DATE, 'Month') as month_name,
	ROUND(SUM(s.order_quantity * p.product_price),2) as monthly_sales
FROM sales_data s
JOIN product_lookup p ON s.product_key = p.product_key
JOIN calender_lookup c ON s.order_date = c.date
GROUP BY month,month_name
ORDER BY month;

--Q4 Which 10 products are sold the most and also show the revenue generated by these products.
SELECT 
	p.product_name as product_name,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM sales_data s
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_orders DESC
LIMIT 10;

--Q5 Which country has the highest number of total orders?
SELECT 
	t.country,
	COUNT(DISTINCT order_number) AS total_unique_orders
FROM sales_data s
JOIN territory_lookup t ON s.territory_key = t.sales_territory_key
GROUP BY t.country
ORDER BY total_unique_orders DESC;

--MEDIUM
--Q6 Identify "Inactive Customers"—those who haven't placed an order.
SELECT 
    c.customer_key,
    INITCAP(c.first_name) AS first_name,
    INITCAP(c.last_name) AS last_name,
    c.email_address
FROM customer_lookup c
LEFT JOIN sales_data s ON c.customer_key = s.customer_key
WHERE s.customer_key IS NULL;

--Q7 Identify all products in the Product_Lookup table that have never been sold.
SELECT 
    p.product_key,
    p.product_name,
    p.product_sku,
    p.product_price
FROM product_lookup p
LEFT JOIN sales_data s ON p.product_key = s.product_key
WHERE s.product_key IS NULL;

--Q8 Find the top 10 customers by total spend. Show their full name, email address, orders placed and revenue.
SELECT 
	c.customer_key,
	CONCAT(INITCAP(c.first_name),' ',INITCAP(c.last_name)) as full_name,
	c.email_address,
	COUNT(DISTINCT order_number) AS total_orders,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY c.customer_key,INITCAP(c.first_name),INITCAP(c.last_name),c.email_address
ORDER BY revenue DESC
LIMIT 10;

--Q9 Generate a report that identifies products that have both high sales volume (over 10,000 units) and significant return volume (over 5,000 units).
SELECT 
    p.product_name,
    SUM(s.order_quantity) AS total_sold,
    SUM(r.return_quantity) AS total_returned
FROM product_lookup p
JOIN sales_data s ON p.product_key = s.product_key
JOIN returns_data r ON p.product_key = r.product_key
GROUP BY p.product_name
HAVING SUM(s.order_quantity) > 10000
   AND SUM(r.return_quantity) > 5000
ORDER BY total_returned DESC;


--Q10 Analyze total revenue broken down by the Day of the Week.
SELECT 
	extract(DOW from c.date) as day,
	to_char(date::DATE, 'FMDay') as day_name,
	ROUND(SUM(s.order_quantity * p.product_price),2) as day_of_week_sales
FROM sales_data s
JOIN product_lookup p ON s.product_key = p.product_key
JOIN calender_lookup c ON s.order_date = c.date
GROUP BY day,day_name
ORDER BY day;

	
--Q11 Fragment customers into 'Low' (<$5k), 'Medium' ($5k-$10k), and 'High' (>$10k) income brackets and find the total revenue generated by each bracket.
WITH customer_revenue AS (
SELECT 
	c.customer_key,c.first_name,c.last_name,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY revenue DESC
),
tiered_customers AS (
SELECT 
		*,
		CASE
			WHEN revenue > 10000 THEN 'High'
			WHEN revenue between 5000 and 10000 THEN 'Medium'
			ELSE 'Low'
		END AS revenue_tier
FROM customer_revenue
)
SELECT 
	revenue_tier,
	SUM(revenue) as revenue
FROM tiered_customers
GROUP BY revenue_tier
ORDER BY revenue DESC;

--Q12 Calculate the monthly revenue and the percentage change compared to the previous month.
WITH monthly_sales AS (
SELECT 
	to_char(date::DATE, 'YYYY-MM') as month,
	ROUND(SUM(s.order_quantity * p.product_price),2) as monthly_revenue
FROM sales_data s
JOIN product_lookup p ON s.product_key = p.product_key
JOIN calender_lookup c ON s.order_date = c.date
GROUP BY montH
ORDER BY month
),
monthly_revenue_comparision AS (
SELECT
	month,monthly_revenue,
	LAG(monthly_revenue) OVER(ORDER BY month) as previous_month_revenue
FROM monthly_sales
)
SELECT *,
	CONCAT(ROUND(((monthly_revenue - previous_month_revenue) / previous_month_revenue) * 100,2),'%')  as mom_growth_pct
FROM monthly_revenue_comparision;

--Q13 Find the top 3 spending customers within each occupation category.
WITH customer_spending AS (
SELECT 
	c.customer_key,
	INITCAP(c.first_name) as first_name,
	INITCAP(c.last_name) as last_name,
	c.occupation,
	ROUND(SUM(s.order_quantity * p.product_price),2) as revenue
FROM customer_lookup c
JOIN sales_data s ON c.customer_key = s.customer_key
JOIN product_lookup p ON s.product_key = p.product_key
GROUP BY c.customer_key,c.first_name,c.last_name,c.occupation
ORDER BY revenue DESC
),
ranked_customers AS ( 
SELECT *,
	DENSE_RANK() OVER(PARTITION BY occupation ORDER BY revenue DESC) AS ranking
FROM customer_spending
)
SELECT *
FROM ranked_customers
WHERE ranking <=3

--Q14 Calculate a 7-day rolling average of revenue to smooth out daily sales spikes.
WITH daily_revenue AS (
SELECT 
	c.date,
	ROUND(SUM(s.order_quantity * p.product_price),2) as daily_sales
FROM sales_data s
JOIN product_lookup p ON s.product_key = p.product_key
JOIN calender_lookup c ON s.order_date = c.date
GROUP BY date
ORDER BY date 
)
SELECT 
	*,
	ROUND(AVG(daily_sales) OVER( ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) as moving_avg_7_day
FROM daily_revenue

--Q15 Write a query that identifies every instance where a customer had a "silent gap" of 730 days (2 years) or more between any two consecutive orders.
WITH customer_order_gaps AS (
    SELECT 
        s.customer_key,
		INITCAP(c.first_name) as first_name,
		INITCAP(c.last_name) as last_name,
        order_date AS current_order,
        LAG(order_date) OVER (PARTITION BY s.customer_key ORDER BY order_date) AS previous_order
    FROM sales_data s
	JOIN customer_lookup c on s.customer_key = c.customer_key
)
SELECT 
    customer_key,
	first_name,
	last_name,
    previous_order AS original_purchase,
    current_order AS return_purchase,
    (current_order - previous_order) AS days_between
FROM customer_order_gaps
WHERE (current_order - previous_order) >= 730
ORDER BY days_between DESC;